RESUME_KEYWORDS = [
    "AI Engineer", "Data Scientist", "Machine Learning Engineer",
    "NLP Engineer", "NLP Data Scientist", "Generative AI",
    "LangChain", "RAG", "GPT-4", "LLaMA", "Gemini", "Copilot", "Mistral",
    "Hugging Face", "FAISS", "Pinecone", "ChromaDB", "Prompt Engineering",
    "Sentence Transformers", "BioBERT", "ClinicalBERT", "Cortex",
    "TensorFlow", "PyTorch", "scikit-learn", "XGBoost", "LightGBM", "CatBoost",
    "Keras", "spaCy", "NLTK", "OpenCV", "YOLO", "Gensim",
    "AWS SageMaker", "GCP Vertex AI", "Azure ML", "Azure ML Studio",
    "S3", "EC2", "Glue", "Athena", "Redshift", "BigQuery", "Synapse",
    "Data Lake", "Kinesis", "Dataflow",
    "MLflow", "FastAPI", "Docker", "Kubernetes", "AKS",
    "Apache Airflow", "CI/CD", "Jenkins", "GitHub Actions",
    "Terraform", "Git",
    "Snowflake", "Databricks", "BigQuery", "Redshift",
    "PySpark", "Kafka", "Hadoop", "PostgreSQL", "MySQL", "MongoDB",
    "Cassandra", "NoSQL", "Polars", "Dask",
    "Tableau", "Power BI", "Quicksight", "Matplotlib", "Seaborn", "MicroStrategy",
    "Python", "SQL", "R", "Java", "C++", "Julia", "Scala",
    "Optimization", "Bayesian", "Hypothesis Testing", "A/B Testing",
]

SEARCH_TITLES = [
    "AI Engineer",
    "Machine Learning Engineer",
    "Data Scientist",
    "NLP Engineer",
    "Generative AI Engineer",
    "MLOps Engineer",
    "NLP Data Scientist",
    "AI/ML Engineer",
    "Deep Learning Engineer",
    "LLM Engineer",
    "Applied Scientist",
    "Research Scientist ML",
    "Gen AI Engineer",
]
